### ISSUE TITLE
[review] add code comparisons for Boost.FunctionTypes

### ISSUE THREAD

**Issue by badair** [badair/callable_traits#117]
and perhaps with other libraries?

from http://lists.boost.org/Archives/boost/2017/04/234203.php
and http://lists.boost.org/Archives/boost/2017/04/234234.php

**Comment by badair** [comment]
@ldionne I added a code comparison with FunctionTypes [here](http://badair.github.io/callable_traits/doc/html/index.html#callable_traits.introduction.boost_function_types), and also linked to both a FunctionTypes extended example alongside the CallableTraits re-implementation of it (namely Eraserface). Do you think this is sufficient and fair?

**Comment by ldionne** [comment]
Thanks, yeah I think this is sufficient and fair.

**Comment by badair** [comment]
Boost,

If you're looking for the is_invocable issue as linked on my mailing list post, you followed a typo link. Here's the one I meant to post: https://github.com/badair/callable_traits/issues/119
