### ISSUE TITLE
[review] describe library as C++11, add mentions for later standards where applicable

### ISSUE THREAD

**Issue by badair** [badair/callable_traits#118]
from http://lists.boost.org/Archives/boost/2017/04/234234.php

**Comment by ldionne** [comment]
Awesome job, I love the matrix.

**Comment by ldionne** [comment]
You may want to cover future compiler versions where everything works by saying something like "Clang >= 4.0.0". Otherwise you'll have to revise these tables every time a new supported compiler is released, which may be a lot of work (and will end up with very large matrices).

**Comment by badair** [comment]
@ldionne I considered this, but I think this would be misleading. I am only comfortable listing compilers that I have tested. While I have made every effort to future-proof the code using feature detection macros, compiler regressions are possible.

**Comment by ldionne** [comment]
Fair enough!
