### ISSUE TITLE
[review] bring back is_invocable, etc

### ISSUE THREAD

**Issue by badair** [badair/callable_traits#119]
http://lists.boost.org/Archives/boost/2017/04/234298.php

**Comment by badair** [comment]
also from @ricejasonf

**Comment by ricejasonf** [comment]
I think it is spelled `is_invocable` at least in the proposed standard.

http://en.cppreference.com/w/cpp/types/is_invocable

**Comment by badair** [comment]
@ricejasonf Ah, thanks. I just misspelled it on the Boost mailing list too.

**Comment by badair** [comment]
I only added back is_invocable and is_invocable_r. I think the nothrow versions aren't worth the trouble for now.
