### ISSUE TITLE
Why use parent_ in parent_class_of?

### ISSUE THREAD

**Issue by ldionne** [badair/callable_traits#137]
To me, `parent` makes it look like inheritance. Why not simply `class_of` or something like that? Also, if there's a reason for the current name, I think adding a short explicative note in the documentation would be nice.

**Comment by pdimov** [comment]
+1, I also think that the simple `class_of` makes more sense.

**Comment by badair** [comment]
Agreed; will fix.

**Comment by badair** [comment]
fixed via a2db2a887306fbc3dabb817b79db1ab53a2cb853
