### ISSUE TITLE
should parameter "container operations" go in their own namespace?

### ISSUE THREAD

**Issue by badair** [badair/callable_traits#28]
Reasons I'm asking:
- names like `push_arg_front` don't imply that multiple types can be pushed (they can)
- names like `push_args_front` put too much emphasis on the fact that multiple types can be pushed
- `callable_traits::push_front` is too generic
- `callable_traits::parms::push_front` or something like that might be nice.

Thoughts?

**Comment by ricejasonf** [comment]
Just my cursory viewpoint.. I would say yes but make it `params` or maybe even `args`. The `args` function could be something like `to_tuple` or just `get`.

**Comment by badair** [comment]
@ricejasonf Thanks for the input. I agree that `params` would be good. Right now I'm preparing a PR for a Boost.TypeTraits fork with all of the CallableTraits features integrated. This will be a good thing for me to ask on the mailing list.

**Comment by badair** [comment]
Won't do for now
