### ISSUE TITLE
Consider accepting types in can_invoke

### ISSUE THREAD

**Issue by ldionne** [badair/callable_traits#77]
In the "Quick example", you say of `can_invoke`

> ```c++
> // Note that since can_invoke models std::invoke,
> // only a value-style function is defined.
> ```

I find myself wondering why you don't also provide a type-based interface. I could imagine something like

```c++
can_invoke<foo, std::nullptr_t>()
```

instead of 

```c++
can_invoke(foo{}, nullptr)
```

In particular, imagine the following use case:

```c++
template <typename F, typename ...Args, typename = std::enable_if_t<
    can_invoke<F, Args...>()
>>
auto f(F f, Args ...args) {
    // invoke f with args

    // maybe do something else
}
```

I'm not saying it's a bad decision to provide only the value-based API here, but you'd have to at least document the rationale for breaking the consistency of the rest of the API.

**Comment by badair** [comment]
Fixed in 2877891 (documentation still needs updating). Thanks!
